language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck --stacktrace
